"""add_fleet_type_and_twin_models

Revision ID: 3556bfbb2d06
Revises: 599fe8857ded
Create Date: 2026-08-29 16:59:14.282717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3556bfbb2d06'
down_revision: Union[str, None] = '599fe8857ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('fleet_type', sa.Enum('AUTONOMOUS', 'MANUAL', name='fleettypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'fleet_type')
    # ### end Alembic commands ###
