"""init

Revision ID: 599fe8857ded
Revises: 
Create Date: 2026-08-29 15:48:28.476917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '599fe8857ded'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('hour_meter', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPTIMO', 'ALERTA', 'CRITICO', name='equipmentstatus'), nullable=False),
    sa.Column('last_intervention_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'TECNICO', 'LECTURA', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('equipment_telemetry',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('equipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('equipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVO', 'CORRECTIVO', 'PREDICTIVO', name='maintenancetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_orders')
    op.drop_table('equipment_telemetry')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
